apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin: AgCllfhBNg96BZoaWKHS1q3/GyNSRviiKyPplitFYX/up2wMWERT5GGZQaxC8ZmBcUaAmSFrxqOK5Puw+mojokbuV8mwsg6DhGKbUybhT+Cwuim/TmRQ7OIbj8vC42pyJ7Io7r6JJrhtK/xmkLYpJOOi88iGbbrDMg5Ft5Q1hDMee1tMZgNDvAD9orEtJ497HBGMq8Smc0X1rn7++4SCZrWcxPiLIN0l+qgh+XfXyQQR+yMaorSjb+4a6sgED8bdMxeU9PGnOFEzY+/hgRAQp7TEkijbiB4q9MEIfWTKrrTrhbVJKDHKuP306jnCr2BztxnWD2La9vxva4ChdE63vHgVTww0KLZLhY3UX7F4Go6+8r2f0vN3BzW95btiMRtRwcAN29ntGPDvshxbwTNyEYvxxHcmSRd2woWPdUzqIOWHzGlzLFHcAx5/pLAv7NwatZ0GVAE7R7NsN0+tV3ug8rOjFu/ZERWqDeIR3D4skapKdUCGbi3/GxJKArzFJPwyPEsg8AZS5x4nq1oYw/Yyg0vNdJMpNegE/C5QMvSPnbkRsU3zDSk3yWUaoYTRey8g83DXp+FkfO7HLUu3bpxrh6bydvvvKArLJGlAV4HCOk8fxFUM4N5rBnz2RXdTDwQ8jPJ1iJxWTROko93nD5mhqNnT1hCPbjnMu0+RsnMNKAujlGPAiw06nq7dhn8C7sjuDmETuE28Lik=
    password: AgBQU8cXIiKTqXrUdEGcPPpRf+pJ7aBAlrWpqcDG21qu5u5OIBg1rtVITGsFFoY/b8WmUz6m774Hh2SMosLDXy41dUsqobyTIv3SlFI65fjFTiNGqiAsNPQPhJCB1z0zLoNE19mG6VYks6TlhHuc+S8NMwEm1Qo5rwH/EI5173IYAmqlDk9P3rSngVvTLwVh4u0+35u5tqZB3xNogJbm5eAJQ8wvjAROTx7vgpa3KhCA0mpe4+/jq5z05fDn82lIiaTGbypTWS73rAHk0LoSWytCDR+27V/tkAYRVt4lnN4mirvFeIc5G96hZcfPtGbXqkGALj4TIuaEwCK/vADtIAVNAHqPabIUwM6fSq4TX/kBg0aYP9pVn6jXOp1sOm/d5RgihgSrQwGoIXn+UKkxybUHtLZXgwwehay/O3qFthmIdsCl/TBdyjjRIsV/LUUz9LvZJ5VQaj4OC6CGVFgkisP+MwrC+IgRH6s31H/MCyo+p9ECKYAu9KPI5QpsbDvCoLkqY1ymGs9m9/t8/xVb7BzlQHHpL1MWPI4WSygwsjneCYATMvxb5GDiBrgcu54/MwzRptl5bcb6cZcf2JM8lYeCjh9689KTbWxsYiQxy2PjTNmATvnHnfXvOIXFkIDBm2Kc3zZuoVMoQcW/NLiw9H6kXUlFQAPulujKu0trsnXiZNnZtzTV6ZI8y1roNi7GNq905iFphsPdDnqGbmWUBg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring
status: {}
