---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin: AgCmW9PCjGueLmcUfv3lDqwxOMPwJWGBikoiDrMeRo9byk2iA8skyCihNiVMC+BBEtR3zIw5xZlQeMOF5e5i/lxHKG1T7hviuSOp3p8KtzXyWiztZqpRXQZ5bIUrQLcCsRAgIk/o5gTH8+xtDXQhnsf6  IjvM3BoYpoJXz3oalWySSXgsFsl/epRmFrD0Gjut0BPmLUT9JLQgdeX2MzESpKyGH39d3VI1aF9gGg2VnK2t2nrNqVthkehcqYyR/JfBelLjiCp2v3LxCNaFWf/flRdYah/TenKIbtaSJKHw6ZZMjjoX+rUPRrgnTEh  tMMQNiHQXeB28mj3O4mqMDw3sSIcT9RZXnI5uZM6Fh13QtTtafNhiDf0BS+IhYRnfMitHLDlgzw8OOObLBtv4tQVfGrQcqq1lTL4Y9YP1Xn1r2LLko4Bs/XesBQAB2bZVTru65DIuh7cqzcrjwVUk0msAkBSwJZBP28  NNyZFejhuRz8zSTXpEW18ClpiQgU46T1946xLme9EyCHTs34v0/nYcgMdIC3M6Ngqn68afSFC47Z7C+6yu9kLxTA0Bohya//fWftLNTiABj+VAufZEt7Me970S6WFtTJSn3fsuMNw0edIl3GUQavLDCoyyNHhK/DoIe  YmC6ZCSS3MpM6fTjJxKB5BCZCDyKzAnkow1Szt5QZ4EmeYxGtp3gPuJn5hgKRuYevN3Nz3UHKQ=
    password: AgA2dXkYdIl6Gnp6b8F7Ao/4eQCgtUX2q4QJDaY1Kj76uVj3EofBJX/+h20Srr9A+4VWjdnH/mgqtmyeUzOgkklG4TjxfeFL/AZrZIRv5lmtdwJ7ZvIFPIxC5zSNkGFcaFvyiy0nNMABZmOlM+2U0  i0EfT35BCBchH7Vj/pFWbDRHQvlRJ50NjPBBuiTWdKWFXUBWouiYCWsfDVhv6nz6yWNEmBsFndxl4vzabapyiXVGEPe1+6yf5iIUL5vbff/flmFq43WFvehirg5GzdkbAaXwaU2lT8475fOIb9nK2mVSIvl1qeRqGJV  GWeY9NZf73pENYAyBpf1jrqwbru742hZe02rhMSgi6UUx7phTUzLQkBv+j/JV7LFYuPDBgGVCuwMvtDw3G8EDaihY4GJoQaPGZMlqF9YleRz//eqbgGfzuUlVzdIzDiEDQIWPRPdLHLleuP0TlUsdItcL0Dc8/7RHc/  GzyQNVD/UHybN9L3pgTKcL4RY3B9ZCgXG8FbpH6eGhw7UlmvGE0Z//pMNAx+gzgAUA0S7jenxSAunZjtBH04Gw7WtHegODUfpG2i1OvsS89kl4hfzlibc7QBYH4mOzaJWd8ErJ9aeYyjxoGFI6c/GSrdoEovXUAfgb5  fTBro/YDdUqB4Y2gpU387+AveNSeaAcTYJrYYg0Q4Hul9ymfFdVFXoS0tpfJ6XGCWY5JvnJBs1XuksiatAJmjF/g==
  template:
    metadata:
      name: grafana-auth
      namespace: monitoring
