apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: playerbio
  name: playerbio-app
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: playerbio
  endpoints:
  - port: api
