apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: playerbio
  name: playerbio-app
  labels:
    team: devops
    k8s-apps: playerbio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: playerbio
  namespaceSelector:
    matchNames:
    - playerbio
  endpoints:
  - port: api
