{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "playerbio.serviceAccountName" . }}
  labels:
{{ include "playerbio.labels" . | indent 4 }}
{{- end -}}
