---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: playerbio
  namespace: playerbio
  annotations:
    fluxcd.io/automated: 'true'
spec:
  helmVersion: v2
  releaseName: playerbio
  chart:
    git: git@github.com:nuriel77/playerbio.git
    path: charts/playerbio/
    ref: master
  values:
    replicas: 5
    image:
      repository: nuriel77/playerbio
      tag: v0.1.2
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 150m
        memory: 64Mi
   ### Enable if more than one nodes in the k8s cluster
   ### and if number of nodes are equal to or greater
   ### than the number of replicas.
   # affinity:
   #   podAntiAffinity:
   #     requiredDuringSchedulingIgnoredDuringExecution:
   #     - labelSelector:
   #         matchExpressions:
   #         - key: app.kubernetes.io/instance
   #           operator: In
   #           values:
   #           - playerbio
   #       topologyKey: kubernetes.io/hostname
