---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: playerbio
  namespace: playerbio
  annotations:
    fluxcd.io/automated: 'true'
spec:
  helmVersion: v2
  releaseName: playerbio
  chart:
    git: git@github.com:nuriel77/playerbio.git
    path: charts/playerbio/
    ref: master
  values:
    replicas: 5
    image:
      repository: nuriel77/playerbio
      tag: v0.1.2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - playerbio
          topologyKey: kubernetes.io/hostname
