{
 "title": "PlayerBio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Container Restarts",
   "type": "graph",
   "description": "Container restarts registered in the past 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"playerbio\"}[5m])"
    }
   ]
  },
  {
   "title": "Number of replicas",
   "type": "graph",
   "description": "Number of replicas available/unavailable",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"playerbio\"}"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"playerbio\"}"
    }
   ]
  },
  {
   "title": "Network output bytes",
   "type": "graph",
   "description": "Per pod and total as seen by erlang metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erlang_vm_statistics_bytes_output_total[$interval])) by (pod)"
    },
    {
     "expr": "sum(rate(erlang_vm_statistics_bytes_output_total[$interval]))"
    }
   ]
  },
  {
   "title": "Network received bytes",
   "type": "graph",
   "description": "Per pod and total as seen by erlang metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(erlang_vm_statistics_bytes_received_total[$interval])) by (pod)"
    },
    {
     "expr": "sum(rate(erlang_vm_statistics_bytes_received_total[$interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage in Namespace",
   "type": "graph",
   "description": "CPU usage past 5 minutes - total in namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"playerbio\"}[$interval])) by (namespace) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage per pod",
   "type": "graph",
   "description": "CPU usage per pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\",namespace=\"playerbio\"}[$interval])) by (pod) * 100"
    }
   ]
  },
  {
   "title": "Memory Total per Pod",
   "type": "graph",
   "description": "Erlang memory total bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (erlang_vm_memory_bytes_total)"
    }
   ]
  },
  {
   "title": "Memory Usage by k8s",
   "type": "graph",
   "description": "Total memory usage in namespace, and memory usage per container as reported by k8s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"playerbio\"}"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"playerbio\"}) by (namespace)"
    }
   ]
  }
 ]
}