apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: splunk-connet
  namespace: splunk
spec:
  helmVersion: v3
  releaseName: splunk-connect
  chart:
    git: https://github.com/splunk/splunk-connect-for-kubernetes.git
    path: helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging
    ref: release/1.4.0
  values:
    global:
      logLevel: info
      splunk:
        hec:
          # Token via sealed-secrets created secret obj
          token: 00000000-0000-0000-0000-000000000000
          host: splunk-s1-standalone-headless
          port: 8088
          protocol: https
          insecureSSL: true
      kubernetes:
        clusterName: "microk8s-cluster"
      prometheus_enabled: true
    secret:
      create: false
      name: splunk-kubernetes-logging
    containers:
      path: /var/log
      pathDest: /var/lib/docker/containers
      logFormatType: cri
      # Specify the log format for "cri" logFormatType
      # It can be "%Y-%m-%dT%H:%M:%S.%N%:z" for openshift and "%Y-%m-%dT%H:%M:%S.%NZ" for IBM IKS
      logFormat:
