name: Build Docker
on:
  push:
    paths:
      - "src/Dockerfile"
      - "src/docker-compose.yml"
  pull_request:
    paths:
      - "src/docker/Dockerfile"
      - "src/docker-compose.yml"
jobs:
  build:

    name: Build player bio - Docker
    runs-on: ubuntu-latest
    steps:

      - name: Prepare Environment
        uses: actions/checkout@v2

      - name: Build HORNET Docker image
        run: docker build . --file src/Dockerfile --build-arg TARGET_ENV=prod --tag playerbio:latest
        timeout-minutes: 300

      - name: Test HORNET Docker image
        run: docker run --rm --name testing playerbio:latest /app/bin/player_bio version 2>/dev/null | grep -q "player_bio"
        timeout-minutes: 1
